
# Aggregates
aggs:
- UserAgg: &User
    id: g
    firstName: s
    lastName: s

# Views
views:
- UserView: &UserView
    id: g
    firstName: s
    lastName: s

# Slices
slices:
  - AddUser:
      agg: *User
      command:
        name: AddUser # The command name is optional since by default it will match the name of the Slice
      event:
        name: AddedUsed # The event name should be the past tense of the command
        props:
          id: g
          firstName: s
          lastName:
      views:
        - *UserView

  - RenameUser: # In this slice we don't have a command specified. The command is inferred and will be named after the slice ('RenameUser' in this case)
      agg: *User
      event:
        name: RenamedUser
        props:
          id: g
          firstName: s
          lastName: s
      views:
        - << : *UserView
          id: x
          firstName: x

  - ReAgeUser: # In this slice we don't have a command specified. The command is inferred and will be named after the slice ('RenameUser' in this case)
      story: 'https://www.example.com/12345'
      status: InDev
      agg: *User
      event:
        name: ReAgedUser
        props:
          id: g
          age: int
      views:
        - << : *UserView
          id: x
          age: in
